-- Lethe Schema
--
-- IMPORTANT: The canonical schema is the ordered migration set under
-- internal/db/migrations/. This file is for reference only.
--
-- To see the current schema, apply all migrations to a fresh database:
--
--   go run ./cmd/lethe --db ./lethe.db
--
-- Or inspect migrations directly:
--
--   ls -la internal/db/migrations/
--
-- Schema versions:
--   001_init.sql              — agents, projects, sessions, checkpoints, events, session_links
--   002_add_session_key.sql   — stable session_key for OpenClaw
--   003_add_token_budget.sql  — per-session token budget
--   004_add_lifetime_tokens.sql — cumulative token tracking
--   005_add_threads.sql       — named threads for open questions
--   006_project_scoped_events.sql — project-level events (null session_id)
--   007_unique_session_key.sql — unique index on session_key
--   008_context_assembly_ledger.sql — context assembly observability
--
-- SQLite features used:
--   - WAL mode (journal_mode=WAL)
--   - Foreign keys (foreign_keys=ON)
--   - CHECK constraints (including conditional checks via compound expressions)
--   - Embedded numbered migrations
--
-- For the actual schema, run migrations or inspect the migration files.
